package com.LeoDuarte37.ForgotPassword_Api.service;

/**
 * <h1>OtpService</h1>
 * <p>
 *     This is an interface that specifies some methods
 *     and how to implement them to handle OTP Codes.
 * </p>
 */
public interface OtpService {

    /**
     * Generate OTP Code by key.
     *
     * @param key key that will associate with otp.
     * @return OTP Code.
     */
    Integer generateOtp(String key);

    /**
     * Get OTP Code by key.
     *
     * @param key key associated with otp.
     * @return OTP Code.
     */
    Integer getOtpByKey(String key);

    /**
     * Delete OTP Code from cache using
     * respective key.
     *
     * @param key key associated with otp.
     */
    void clearOtpFromCache(String key);

    /**
     * Verifies if OTP Code exists in cache.
     *
     * @param key key associated with otp.
     * @param otp otp generated by generateOtp method.
     * @return true or false.
     */
    boolean validateOtp(String key, Integer otp);
}
